### ISSUE TITLE
When `!window.IntersectionObserver` errors are thrown.

### ISSUE THREAD

**Issue by Westbrook** [bennypowers/lazy-image#3]
It looks like you're missing coverage for when `IntersectionObserver` isn't available in the browser. Larger scale, it might be fun to have some sort of fallback to a polyfill, but I'd settle for it just loading the assets at runtime for now.

It looks like when you add the following to `initIntersectionObserver`:
```
    if (!window.IntersectionObserver) {
      this.setIntersecting(true);
      return;
    }
```
and swap the method order in `connectedCallback`, like so:
```
  connectedCallback() {
    this.attachShadow({mode: 'open'})
      .appendChild(getTemplate(this).content.cloneNode(true));
    this.initIntersectionObserver(this);

    this.placeholder = this.getAttribute('placeholder')
  }
```
That this functionality is achieved.

If that seems copacetic to you, I'm happy to submit a PR, or if there is a different approach, I'd be happy to take notes or wait for your our addition to support this area.

Thanks!

**Comment by bennypowers** [comment]
Thanks for the issue!

Feature detection with fallback should be the way to go. I don't want to add in any polyfill or workaround since that 6kb size is nice.

Please send that PR, and would you please add a note in the README that IO polyfill may be required for some browsers.

Semantically speaking, I think it would be better to do:

```js
  connectedCallback() {
    this.attachShadow({mode: 'open'})
      .appendChild(getTemplate(this).content.cloneNode(true));

    ('IntersectionObserver' in window)
      ? this.initIntersectionObserver(this)
      : this.setIntersecting(true)

    this.placeholder = this.getAttribute('placeholder')
  }
```
